upstream member-service {
    server member-service:8080;
}
upstream order-service {
    server order-service:8081;
}
upstream auth-service {
    server auth-service:8082;
}
upstream bff {
    server bff:8000;
}

server {
    listen 80;

    location /auth {
        proxy_pass http://auth-service;
    }
    location /members {
        proxy_pass http://member-service;
    }
    location /products {
        proxy_pass http://member-service;
    }
    location /orders {
        proxy_pass http://order-service;
    }
    location /stats {
        proxy_pass http://order-service;
    }
    location /bff {
        proxy_pass http://bff;
    }
}
